### ISSUE TITLE
Autodetect Error

### ISSUE THREAD

**Issue by Chaotix13567** [Xcelled/mabicommerce#14]
When I attempt to open up the commerce trade window with autodetect on, I get an error message that contains the following:
```
System.Exception: Expected Long, got String.
   at MabiCommerce.Network.Packet.GetLong()
   at MabiCommerce.UI.MainWindow.InfoUpdate(Packet packet)
   at MabiCommerce.UI.MainWindow.HandlePacket(Packet packet)
   at MabiCommerce.UI.MainWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```
I have absolutely no idea what this means, but maybe someone here does :P If so, please let me know if there is anything I can do to fix it.

**Comment by Xcelled** [comment]
This probably means they changed the packet structure of the commerce info. Someone would have to log the new structures and update the parsing code. Unfortunately i have neither the time nor inclination to do this. I woukd accept a pull request though.

**Comment by Chaotix13567** [comment]
After some poking around with MabiPale2 (and trial and error), it appears that the new codes are
Commerce Info Request Op: 0xAAB6
Commerce Info Update Op: 0xAC72
Product List Request Op: 0xAAAA
Or at least these work for me.

**Comment by Xcelled** [comment]
@Chaotix13567 if you'd be willing to make those changes to the code and submit a PR, I can get it merged.
